spring.application.name=experience


# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Initial admin
experience.initial-admin.username=${EXPERIENCE_INITIAL_ADMIN_USERNAME:admin}
experience.initial-admin.password=${EXPERIENCE_INITIAL_ADMIN_PASSWORD:admin123}