# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# MinIO
experience.minio.endpoint=${EXPERIENCE_MINIO_ENDPOINT}
experience.minio.access-key=${EXPERIENCE_MINIO_ACCESS_KEY}
experience.minio.secret-key=${EXPERIENCE_MINIO_SECRET_KEY}
experience.minio.bucket=${EXPERIENCE_MINIO_BUCKET:experience}
