spring.application.name=experience

spring.profiles.active=dev

# Initial admin
experience.initial-admin.username=${EXPERIENCE_INITIAL_ADMIN_USERNAME:admin}
experience.initial-admin.password=${EXPERIENCE_INITIAL_ADMIN_PASSWORD:admin123}

# MinIO
experience.minio.endpoint=${EXPERIENCE_MINIO_ENDPOINT:http://localhost:9000}
experience.minio.access-key=${EXPERIENCE_MINIO_ACCESS_KEY:minioadmin}
experience.minio.secret-key=${EXPERIENCE_MINIO_SECRET_KEY:minioadmin}
experience.minio.bucket=${EXPERIENCE_MINIO_BUCKET:experience}
